# Generated by Django 2.1.5 on 2019-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfpost',
            name='pdf',
            field=models.FileField(upload_to='C:\\sumalyze\\media'),
        ),
    ]
