# Generated by Django 2.1.5 on 2019-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpost',
            name='index',
            field=models.TextField(null=True),
        ),
    ]
