# Generated by Django 2.2.1 on 2019-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20190517_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfpost',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
