# Generated by Django 2.1.5 on 2019-05-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiopost',
            old_name='audio',
            new_name='pdf',
        ),
    ]
